import java.util.*;
class solution
{
    public static void main(String[]args)
    {
        Scanner scan=new Scanner(System.in);
        int t,i,j,k,l;
        String str=scan.nextLine();
        String ptr[]=str.split("\\s+");
        for(i=0;i<ptr.length;i++)
        {
        	char A[]=ptr[i].toCharArray();
        	for(j=0;j<ptr[i].length();j++)
        	{
        		if(A[j]=='a'||A[j]=='z')
        		{
        			if(A[j]=='a')
        			{
        				A[j]='z';
        			}
        			else
        			{
        				A[j]='a';
        			}
        		}
        		if(A[j]=='b'||A[j]=='y')
        		{
        			if(A[j]=='b')
        			{
        				A[j]='y';
        			}
        			else
        			{
        				A[j]='b';
        			}
        		}
        		if(A[j]=='c'||A[j]=='x')
        		{
        			if(A[j]=='c')
        			{
        				A[j]='x';
        			}
        			else
        			{
        				A[j]='c';
        			}
        		}
        		if(A[j]=='d'||A[j]=='w')
        		{
        			if(A[j]=='d')
        			{
        				A[j]='w';
        			}
        			else
        			{
        				A[j]='d';
        			}
        		}
        		if(A[j]=='e'||A[j]=='v')
        		{
        			if(A[j]=='e')
        			{
        				A[j]='v';
        			}
        			else
        			{
        				A[j]='e';
        			}
        		}
        		if(A[j]=='f'||A[j]=='u')
        		{
        			if(A[j]=='f')
        			{
        				A[j]='u';
        			}
        			else
        			{
        				A[j]='f';
        			}
        		}
        		if(A[j]=='g'||A[j]=='t')
        		{
        			if(A[j]=='g')
        			{
        				A[j]='t';
        			}
        			else
        			{
        				A[j]='g';
        			}
        		}
        		if(A[j]=='h'||A[j]=='s')
        		{
        			if(A[j]=='h')
        			{
        				A[j]='s';
        			}
        			else
        			{
        				A[j]='h';
        			}
        		}
        		if(A[j]=='i'||A[j]=='r')
        		{
        			if(A[j]=='i')
        			{
        				A[j]='r';
        			}
        			else
        			{
        				A[j]='i';
        			}
        		}
        		if(A[j]=='j'||A[j]=='q')
        		{
        			if(A[j]=='j')
        			{
        				A[j]='q';
        			}
        			else
        			{
        				A[j]='j';
        			}
        		}
        		if(A[j]=='k'||A[j]=='p')
        		{
        			if(A[j]=='k')
        			{
        				A[j]='p';
        			}
        			else
        			{
        				A[j]='k';
        			}
        		}
        		if(A[j]=='l'||A[j]=='o')
        		{
        			if(A[j]=='l')
        			{
        				A[j]='o';
        			}
        			else
        			{
        				A[j]='l';
        			}
        		}
        		if(A[j]=='m'||A[j]=='n')
        		{
        			if(A[j]=='m')
        			{
        				A[j]='n';
        			}
        			else
        			{
        				A[j]='m';
        			}
        		}
        	}
        	ptr[i]=new String(A);
        }
        for(k=0;k<ptr.length;k++)
        {
        	System.out.print(ptr[k]+" ");
        }
    }
}